### ISSUE TITLE
Keypad K5 

### ISSUE THREAD

**Issue by Halowp** [Antecer/antecer.github.io#3]
Hello 

I use this keypad for 2 years now, and i up to date the firmware (2.0.0.3) by the online update on the application.

 When i click on the keypad the cursor go to the top left corner i tried change USB port 2.0 and 3.0 restart my PC its not working.  
 
I try back to go to the old version (1.3.1.0) the application say (Device type verification failed)

**Comment by Antecer** [comment]
If you want download the old version, you need use  the old versiong application.

**Comment by Halowp** [comment]
it work now
