### ISSUE TITLE
Driver won't detect keypad after update.

### ISSUE THREAD

**Issue by Pejdal** [Antecer/antecer.github.io#5]
I had some issues trying to update the software so I tried updating using bootloader, and I think the driver got updated, but now it won't detect the keypad anymore.

(It's the KeypadPro)

**Comment by embedvr** [comment]
I actually have this issue too, any fix?

**Comment by Pejdal** [comment]
Yes! I got it fixed.
I just joined the Discord server and posted my issue, and Antecer himself helped me out through private messages.
