### ISSUE TITLE
App don't recognize keypad anymore

### ISSUE THREAD

**Issue by Sebek421** [Antecer/antecer.github.io#6]
The app (for KeypadPro (ver 3.0.0.9)) was working just fine, but now won't recognize device and when i plug it in there's only weak red light on keypad.
![image](https://user-images.githubusercontent.com/42761238/124328670-59977500-db8a-11eb-92ba-733de1b4db95.png)

**Comment by Antecer** [comment]
try another usb cable, it may broken.
